/*
 icons.js - ESP3D icons file

 Copyright (c) 2020 Luc Lebosse. All rights reserved.

 This code is free software; you can redistribute it and/or
 modify it under the terms of the GNU Lesser General Public
 License as published by the Free Software Foundation; either
 version 2.1 of the License, or (at your option) any later version.

 This code is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 Lesser General Public License for more details.

 You should have received a copy of the GNU Lesser General Public
 License along with This code; if not, write to the Free Software
 Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
*/

import { h } from "preact"
import {
    Activity,
    AlertCircle,
    Aperture,
    Cast,
    CheckCircle,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    Circle,
    Crosshair,
    Delete,
    Download,
    Edit,
    EyeOff,
    Eye,
    File,
    Filter,
    Flag,
    Frown,
    GitCommit,
    Grid,
    HardDrive,
    Heart,
    HelpCircle,
    Home,
    Image,
    Info,
    Layers,
    LifeBuoy,
    List,
    Loader,
    Lock,
    LogOut,
    MapPin,
    Meh,
    Menu,
    MessageSquare,
    MinusCircle,
    Moon,
    MoreHorizontal,
    MoreVertical,
    Move,
    PauseCircle,
    Percent,
    PlayCircle,
    PlusCircle,
    Power,
    RefreshCw,
    Repeat,
    RotateCcw,
    Save,
    Scissors,
    Send,
    Server,
    Settings,
    Slash,
    Sliders,
    Star,
    StopCircle,
    Sun,
    Sunrise,
    Sunset,
    Tag,
    Target,
    Terminal,
    Thermometer,
    Tool,
    Trash2,
    Underline,
    Upload,
    Wind,
    XCircle,
    ZapOff,
    Zap,
} from "preact-feather"

const iconsFeather = {
    None: null,
    Activity: <Activity />,
    AlertCircle: <AlertCircle />,
    Aperture: <Aperture />,
    Cast: <Cast />,
    CheckCircle: <CheckCircle />,
    ChevronDown: <ChevronDown />,
    ChevronLeft: <ChevronLeft />,
    ChevronRight: <ChevronRight />,
    Circle: <Circle />,
    Crosshair: <Crosshair />,
    Delete: <Delete />,
    Download: <Download />,
    Edit: <Edit />,
    EyeOff: <EyeOff />,
    Eye: <Eye />,
    File: <File />,
    Filter: <Filter />,
    Flag: <Flag />,
    Frown: <Frown />,
    GitCommit: <GitCommit />,
    Grid: <Grid />,
    HardDrive: <HardDrive />,
    Heart: <Heart />,
    HelpCircle: <HelpCircle />,
    Home: <Home />,
    Image: <Image />,
    Info: <Info />,
    Layers: <Layers />,
    LifeBuoy: <LifeBuoy />,
    List: <List />,
    Loader: <Loader />,
    Lock: <Lock />,
    LogOut: <LogOut />,
    MapPin: <MapPin />,
    Meh: <Meh />,
    Menu: <Menu />,
    MessageSquare: <MessageSquare />,
    MinusCircle: <MinusCircle />,
    Moon: <Moon />,
    MoreHorizontal: <MoreHorizontal />,
    MoreVertical: <MoreVertical />,
    Move: <Move />,
    PauseCircle: <PauseCircle />,
    Percent: <Percent />,
    PlayCircle: <PlayCircle />,
    PlusCircle: <PlusCircle />,
    Power: <Power />,
    RefreshCw: <RefreshCw />,
    Repeat: <Repeat />,
    RotateCcw: <RotateCcw />,
    Save: <Save />,
    Scissors: <Scissors />,
    Send: <Send />,
    Server: <Server />,
    Settings: <Settings />,
    Slash: <Slash />,
    Sliders: <Sliders />,
    Star: <Star />,
    StopCircle: <StopCircle />,
    Sun: <Sun />,
    Sunrise: <Sunrise />,
    Sunset: <Sunset />,
    Tag: <Tag />,
    Target: <Target />,
    Terminal: <Terminal />,
    Thermometer: <Thermometer />,
    Tool: <Tool />,
    Trash2: <Trash2 />,
    Underline: <Underline />,
    Upload: <Upload />,
    Wind: <Wind />,
    XCircle: <XCircle />,
    ZapOff: <ZapOff />,
    Zap: <Zap />,
}

export { iconsFeather }
