#!/usr/bin/env python3
"""
ESP3D-WEBUI release bundle sizes report.

1. Runs `npm run buildall` (builds all targets/subtargets).
2. Scans dist/ for index.html.gz, index.html.br (and any other artifacts) and collects sizes.
3. Writes a Markdown document with a table: target, subtarget, gzip path/size, brotli path/size.

Usage:
  python tools/release_bundle_sizes.py
  python tools/release_bundle_sizes.py --no-build
  python tools/release_bundle_sizes.py --output docs/BUNDLE_SIZES.md

Copyright (c) 2025 Luc Lebosse. All rights reserved.
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path


def human_size(size_bytes: int) -> str:
    if size_bytes < 1024:
        return f"{size_bytes} B"
    if size_bytes < 1024 * 1024:
        return f"{size_bytes / 1024:.1f} KB"
    return f"{size_bytes / (1024 * 1024):.2f} MB"


def collect_sizes(dist_root: Path) -> list[tuple[str, str, int, str]]:
    """Returns list of (target, subtarget, size_bytes, rel_path)."""
    rows: list[tuple[str, str, int, str]] = []
    if not dist_root.is_dir():
        return rows
    for target_dir in sorted(dist_root.iterdir()):
        if not target_dir.is_dir():
            continue
        target = target_dir.name
        for subtarget_dir in sorted(target_dir.iterdir()):
            if not subtarget_dir.is_dir():
                continue
            subtarget = subtarget_dir.name
            for f in subtarget_dir.rglob("*"):
                if f.is_file():
                    try:
                        size = f.stat().st_size
                    except OSError:
                        size = 0
                    rel = f.relative_to(dist_root)
                    rows.append((target, subtarget, size, str(rel)))
    return rows


def main() -> int:
    parser = argparse.ArgumentParser(description="Build all and report bundle sizes.")
    parser.add_argument(
        "--no-build",
        action="store_true",
        help="Skip npm run buildall; only scan existing dist/.",
    )
    parser.add_argument(
        "--output",
        "-o",
        default=None,
        help="Output Markdown file path (default: dist/BUNDLE_SIZES.md).",
    )
    parser.add_argument(
        "--root",
        default=None,
        help="Repository root (default: parent of tools/).",
    )
    args = parser.parse_args()

    root = Path(args.root) if args.root else Path(__file__).resolve().parent.parent
    dist_root = root / "dist"
    output_path = Path(args.output) if args.output else dist_root / "BUNDLE_SIZES.md"

    if not args.no_build:
        print("Running: npm run buildall")
        r = subprocess.run(
            ["npm", "run", "buildall"],
            cwd=root,
            shell=sys.platform == "win32",
        )
        if r.returncode != 0:
            print("Build failed.", file=sys.stderr)
            return r.returncode

    rows = collect_sizes(dist_root)
    if not rows:
        print("No files found under dist/. Run without --no-build first.", file=sys.stderr)
        return 1

    # Group by (target, subtarget) and sum sizes per artifact; then one row per target/subtarget with main artifact
    by_package: dict[tuple[str, str], list[tuple[int, str]]] = {}
    for target, subtarget, size, rel_path in rows:
        key = (target, subtarget)
        if key not in by_package:
            by_package[key] = []
        by_package[key].append((size, rel_path))

    lines = [
        "# Bundle sizes (dist/)",
        "",
        "Generated by `tools/release_bundle_sizes.py`. Use this table in RELEASE_*.md or docs/FEATURES_AND_BUNDLE.md.",
        "",
        "| Target | Subtarget | Gzip Path | Gzip Size | Brotli Path | Brotli Size |",
        "|--------|-----------|-----------|-----------|-------------|-------------|",
    ]

    total_gz = 0
    total_br = 0
    for (target, subtarget), files in sorted(by_package.items()):
        gz_size = 0
        br_size = 0
        gz_path = None
        br_path = None
        for size, rel in files:
            if rel.endswith('.gz'):
                gz_size = size
                gz_path = rel
                total_gz += size
            elif rel.endswith('.br'):
                br_size = size
                br_path = rel
                total_br += size
        gz_str = human_size(gz_size) if gz_size else 'N/A'
        br_str = human_size(br_size) if br_size else 'N/A'
        gz_path_str = gz_path if gz_path else 'N/A'
        br_path_str = br_path if br_path else 'N/A'
        lines.append(f"| {target} | {subtarget} | {gz_path_str} | {gz_str} | {br_path_str} | {br_str} |")

    lines.extend([
        "",
        f"**Total Gzip size:** {human_size(total_gz)} ({total_gz} bytes).",
        f"**Total Brotli size:** {human_size(total_br)} ({total_br} bytes).",
        "",
    ])

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {output_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
